apiVersion: v1
kind: Service
metadata:
  name: bully-svc
spec:
  clusterIP: None
  selector:
    app: bully
  ports:
  - port: 5000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bully
spec:
  serviceName: "bully-svc"
  replicas: 6
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: bully
  template:
    metadata:
      labels:
        app: bully
    spec:
      containers:
      - name: bully-node
        image: bully-node:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: TOTAL_NODES
          value: "6"
        - name: SERVICE_NAME
          value: "bully-svc"
